/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function RoomFloor({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/roomfloortest.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        position={[0, 0.04, 0]}
        scale={[0.89, 1, 1.23]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-1.53, 0.34, 1.15]}
        scale={[0.23, 0.29, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-1.57, 0.35, 0.65]}
        scale={[0.2, 0.3, 0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-0.76, 0.32, -1.4]}
        scale={[1.02, 0.25, 0.76]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[1.33, 0.83, -1.93]}
        scale={[0.44, 0.77, 0.23]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.desk.geometry}
        material={nodes.desk.material}
        position={[-1.72, 0.4, 2.08]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.03, 0.34, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.table.geometry}
        material={nodes.table.material}
        position={[-0.08, 0.1, 1.64]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.02, 0.04, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mirror_Frame.geometry}
        material={nodes.Mirror_Frame.material}
        position={[1.42, 0.86, 1.92]}
        scale={[0.27, 0.81, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mirror.geometry}
        material={materials["Material.002"]}
        position={[1.42, 0.85, 1.9]}
        scale={[0.27, 0.81, 0]}
      />
    </group>
  );
}

useGLTF.preload("/roomfloortest.gltf");
